shared: &shared
  device_registration_token: <%= ENV['device_registration_token'] %>
  admin_username: <%= ENV['admin_username'] %>
  admin_password: <%= ENV['admin_password'] %>
  secret_key_base: b735f35b559af02f21d7378a1ca7cbcb88b80e4a90d4a990666f09ebf830aa58dff3a74cacb4d1e4eb21818126236a9d3e2e6894fc82da920cf8e0dc8493cae9

development:
  <<: *shared

test:
  <<: *shared

integration:
  <<: *shared
  secret_key_base: <%= ENV['secret_key_base'] %>

production:
  <<: *shared
  secret_key_base: <%= ENV['secret_key_base'] %>
