language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails3.gemfile
script: "bundle exec rake coverage"
before_install:
  - gem install bundler
bundler_args: --retry 5
sudo: false
cache: bundler
