require 'capistrano/setup'
require 'capistrano/deploy'

require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

require 'capistrano/bundler'
require 'capistrano/rails/migrations'
require 'capistrano/rails/assets'
require 'capistrano/rvm'
require 'capistrano/figaro_yml'
require 'capistrano/rails/console'
require 'capistrano/rake'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
